export const ActionType = {
  //CONTROLLER
  HANDLER_PAGE : 'HANDLER_PAGE',

  //USERS
  FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR : 'FETCH_USERS_ERROR',

  FETCH_USERS_BY_ID_REQUEST: 'FETCH_USERS_BY_ID_REQUEST',
  FETCH_USERS_BY_ID_SUCCESS: 'FETCH_USERS_BY_ID_SUCCESS',
  FETCH_USERS_BY_ID_ERROR: 'FETCH_USERS_BY_ID_ERROR',

  //STATS
  FETCH_STATS_REQUEST : 'FETCH_STATS_REQUEST',
  FETCH_STATS_SUCCESS : 'FETCH_STATS_SUCCESS',
  FETCH_STATS_ERROR : 'FETCH_STATS_ERROR',

  FETCH_STATS_BY_ID_REQUEST: 'FETCH_STATS_BY_ID_REQUEST',
  FETCH_STATS_BY_ID_SUCCESS: 'FETCH_STATS_BY_ID_SUCCESS',
  FETCH_STATS_BY_ID_ERROR: 'FETCH_STATS_BY_ID_ERROR',
};