export const ActionType = {

  HANDLER_PAGE : 'HANDLER_PAGE',

  FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR : 'FETCH_USERS_ERROR',

  FETCH_USERS_BY_ID_REQUEST: 'FETCH_USERS_BY_ID_REQUEST',
  FETCH_USERS_BY_ID_SUCCESS: 'FETCH_USERS_BY_ID_SUCCESS',
  FETCH_USERS_BY_ID_ERROR: 'FETCH_USERS_BY_ID_ERROR',
};